---
# TODO: Turn off pond filtration on grid failure
automation:
  - alias: Garden Plug Controller
    description: Always-On Electrical Outlet (with Optional Interlock Switch)
    id: 98d8014a-7c22-4f89-ad8a-b3d812a4e6b1
    use_blueprint:
      path: prehor/always-on-electrical-outlet.yaml
      input:
        outlet_switch_entity: switch.garden_plug
        outlet_switch_child_lock_entity: switch.garden_plug_child_lock
        include_interlock_switch: interlock_switch_enabled
        interlock_switch_entity: binary_sensor.solax_relay_grid_failure
        interlock_switch_delay:
          hours: 0
          minutes: 10
          seconds: 0
