---
id: solax_battery_turn_off_forced_charging
alias: Solax Battery Turn off Forced Charging
triggers:
  - trigger: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.solax_battery_fully_charged
conditions:
  - condition: state
    entity_id: select.solax_remotecontrol_power_control
    state: Enabled Battery Control
actions:
  - action: select.select_option
    target:
      entity_id:
        - select.solax_remotecontrol_power_control
    data:
      option: Disabled
  - action: number.set_value
    target:
      entity_id: number.solax_remotecontrol_active_power
    data:
      value: "0"
  - action: number.set_value
    target:
      entity_id: number.solax_remotecontrol_autorepeat_duration
    data:
      value: "0"
  - action: button.press
    target:
      entity_id: button.solax_remotecontrol_trigger
    data: {}
