---
# Raise a persistent notification when the battery is low and dismiss it when
# the battery is no longer low.
#
# https://andrew-codechimp.github.io/HA-Battery-Notes/community/#battery-low-notification
#

automation:
  - alias: Battery Low Notification
    id: 9a34358f-2436-43a0-b9f3-92032ebd1f1e
    description: Battery Low Notification With Auto Dismiss
    triggers:
      - trigger: event
        event_type: battery_notes_battery_threshold
        event_data:
          battery_low: true
        id: low
      - platform: event
        event_type: battery_notes_battery_threshold
        event_data:
          battery_low: false
        id: high
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: low
            sequence:
              - action: persistent_notification.create
                data:
                  title: "{{ trigger.event.data.device_name }} Battery Low"
                  notification_id: "{{ trigger.event.data.device_id }}-{{ trigger.event.data.source_entity_id }}"
                  message: >-
                    The device has a battery level of {{ trigger.event.data.battery_level }}% {{- '\n' -}}
                    You need {{ trigger.event.data.battery_quantity }}x {{ trigger.event.data.battery_type }}
          - conditions:
              - condition: trigger
                id: high
            sequence:
              - action: persistent_notification.dismiss
                data:
                  notification_id: "{{ trigger.event.data.device_id }}-{{ trigger.event.data.source_entity_id }}"
    mode: queued
    max: 100   # Must be higher than the number of batteries
