---
automation:
  - alias: Room Hana Computer Plug Controller
    description: Always-On Electrical Outlet (with Optional Interlock Switch)
    id: 419fc702-e113-4253-9493-d1ce5840cc97
    use_blueprint:
      path: prehor/always-on-electrical-outlet.yaml
      input:
        outlet_switch_entity: switch.room_hana_computer_plug
        outlet_switch_child_lock_entity: switch.room_hana_computer_plug_child_lock
