---
input_number:
  heatpump_boost_energy_export_treshold:
    name: Energy Export Threshold for Heat Pump Boost
    icon: mdi:hvac
    mode: box
    min: 0
    max: 10000
    step: 100
    unit_of_measurement: kW

  heatpump_boost_energy_import_treshold:
    name: Energy import Threshold for Heat Pump Boost
    icon: mdi:hvac-off
    mode: box
    min: 0
    max: 10000
    step: 100
    unit_of_measurement: kW

template:
  - sensor:
      - name: myVaillant Heating Cylinder Missing Energy
        unique_id: 9a9a2670-5d68-4921-96e4-601dc62a4440
        icon: mdi:water
        device_class: energy
        unit_of_measurement: kWh
        availability: >
          {{
            has_value('sensor.ebusd_ctlv2_z1opmode_value')
            and has_value('sensor.ebusd_ctlv2_hc1maxflowtempdesired_value')
            and has_value('sensor.ebusd_vr_71_sensordata1_s5')
            and has_value('sensor.ebusd_vr_71_sensordata1_s6')
          }}
        attributes:
          last_triggerd: "{{ utcnow().isoformat() }}"
        state: >
          {% if is_state('sensor.ebusd_ctlv2_z1opmode_value', 'off') %}
            0
          {% else %}
            {% set cylinder_volume = 250 %}{# l = kg #}
            {% set water_specific_heat_capacity = 0.0011628 %}{# kWh/(kg * °C) #}

            {% set current_top_cylinder_temperature = states('sensor.ebusd_vr_71_sensordata1_s5') | float(0) %}{# °C #}
            {% set current_bottom_cylinder_temperature = states('sensor.ebusd_vr_71_sensordata1_s6') | float(0) %}{# °C #}
            {% set current_cylinder_temperature = (current_top_cylinder_temperature + current_bottom_cylinder_temperature) / 2 %}{# °C #}

            {% set desired_top_cylinder_temperature = states('sensor.ebusd_ctlv2_hc1maxflowtempdesired_value') | float(0) %}{# °C #}
            {% set desired_bottom_cylinder_temperature = desired_top_cylinder_temperature - 5 %}{# °C #}
            {% set desired_cylinder_temperature = (desired_top_cylinder_temperature + desired_bottom_cylinder_temperature) / 2 %}{# °C #}

            {{
              (desired_cylinder_temperature - current_cylinder_temperature) * water_specific_heat_capacity * cylinder_volume
              if desired_cylinder_temperature > current_cylinder_temperature else 0
            }}
          {% endif %}

  - sensor:
      - name: myVaillant Hot Water Cylinder Missing Energy
        unique_id: cdf7c9db-add7-40cd-9b82-8e80ea366f4f
        icon: mdi:water
        device_class: energy
        unit_of_measurement: kWh
        availability: >
          {{
            has_value('sensor.ebusd_ctlv2_hwcopmode_value')
            and has_value('sensor.ebusd_ctlv2_hwctempdesired_value')
            and has_value('sensor.ebusd_vr_71_sensordata1_s7')
            and has_value('sensor.ebusd_vr_71_sensordata2_s8')
          }}
        attributes:
          last_triggerd: "{{ utcnow().isoformat() }}"
        state: >
          {% if is_state('sensor.ebusd_ctlv2_hwcopmode_value', 'off') %}
            0
          {% else %}
            {% set cylinder_volume = 250 %}{# l = kg #}
            {% set water_specific_heat_capacity = 0.0011628 %}{# kWh/(kg·°C) #}

            {% set current_top_cylinder_temperature = states('sensor.ebusd_vr_71_sensordata1_s7') | float %}{# °C #}
            {% set current_bottom_cylinder_temperature = states('sensor.ebusd_vr_71_sensordata2_s8') | float %}{# °C #}
            {% set current_cylinder_temperature = (current_top_cylinder_temperature + current_bottom_cylinder_temperature) / 2 %}{# °C #}

            {% set desired_top_cylinder_temperature = states('sensor.ebusd_ctlv2_hwctempdesired_value') | float %}{# °C #}
            {% set desired_bottom_cylinder_temperature = desired_top_cylinder_temperature - 5 %}{# °C #}
            {% set desired_cylinder_temperature = (desired_top_cylinder_temperature + desired_bottom_cylinder_temperature) / 2 %}{# °C #}

            {{
              (desired_cylinder_temperature - current_cylinder_temperature) * water_specific_heat_capacity * cylinder_volume
              if desired_cylinder_temperature > current_cylinder_temperature else 0
            }}
          {% endif %}

  - sensor:
      - name: myVaillant Cylinder Missing Energy
        unique_id: d97a5fd1-57ea-41f3-9bfd-ce4c44ad1009
        icon: mdi:water
        device_class: energy
        unit_of_measurement: kWh
        availability: >
          {{
            has_value('sensor.myvaillant_heating_cylinder_missing_energy')
            and has_value('sensor.myvaillant_hot_water_cylinder_missing_energy')
          }}
        attributes:
          last_triggerd: "{{ utcnow().isoformat() }}"
        state: >
          {% set heating_cylinder_missing_energy = states('sensor.myvaillant_heating_cylinder_missing_energy') | float %}
          {% set hot_water_cylinder_missing_energy = states('sensor.myvaillant_hot_water_cylinder_missing_energy') | float %}

          {{ heating_cylinder_missing_energy + hot_water_cylinder_missing_energy }}

automation:
  - alias: Heat Pump Boost Controller
    id: 0a360649-f79b-4437-bc21-63c0e71492df
    triggers:
      # Turn On triggers
      - alias: Energy export to the grid has just started
        id: turn_on
        trigger: numeric_state
        entity_id: sensor.solax_grid_export
        above: input_number.heatpump_boost_energy_export_treshold

      - alias: Battery has just reached full charge
        id: turn_on
        trigger: state
        entity_id: binary_sensor.solax_battery_fully_charged
        to: 'on'

      - alias: Home Assistant was recently started
        id: turn_on
        trigger: state
        entity_id: binary_sensor.homeassistant_recently_started
        to: 'off'
        for:
          minutes: 5

      # Turn Off triggers
      - alias: Battery has begun discharging
        id: turn_off
        trigger: state
        entity_id: binary_sensor.solax_battery_fully_charged
        to: 'off'

      - alias: Energy has just started to be taken from the grid
        id: turn_off
        trigger: numeric_state
        entity_id: sensor.solax_grid_import
        above: input_number.heatpump_boost_energy_import_treshold
        for:
          minutes: 5

      - alias: Home Assistant is shutting down
        id: turn_off
        trigger: homeassistant
        event: shutdown

    actions:
      - choose:
          - conditions:
              - alias: Heat pump boost start requested
                condition: trigger
                id: turn_on

              - alias: The battery is fully charged
                condition: numeric_state
                entity_id: sensor.solax_battery_capacity
                above: 99

              - alias: Energy is exported to the grid
                condition: numeric_state
                entity_id: sensor.solax_grid_export
                above: input_number.heatpump_boost_energy_export_treshold

              - alias: Solar energy is exported to the grid
                condition: numeric_state
                entity_id: sensor.solax_pv_power_total
                above: sensor.solax_grid_export

              - alias: Heatpump cylinder needs some energy
                condition: numeric_state
                entity_id: sensor.myvaillant_cylinder_missing_energy
                above: 0

              - alias: Heat Pump Boost is off
                condition: state
                entity_id: switch.heat_pump_relay_boost_heat_pump
                state: 'off'

            sequence: # []
              - action: switch.turn_on
                target:
                  entity_id: switch.heat_pump_relay_boost_heat_pump
              # TODO: Send notification

          - conditions:
              - alias: Heat pump boost stop requested
                condition: trigger
                id: turn_off

              - alias: Heat Pump Boost is on
                condition: state
                entity_id: switch.heat_pump_relay_boost_heat_pump
                state: 'on'

            sequence: # []
              - action: switch.turn_off
                target:
                  entity_id: switch.heat_pump_relay_boost_heat_pump
              # TODO: Send notification
