---
id: 98d8014a-7c22-4f89-ad8a-b3d812a4e6b1
alias: Keep Garden Plug On
triggers:
  - trigger: state              # The plug has been switched off
    entity_id: switch.garden_plug
    to: "off"
  - trigger: homeassistant      # Home Assistant has just been started
    event: start
    id: homeassistant_start
actions:
  - action: switch.turn_on      # Turn on the plug
    target:
      entity_id: switch.garden_plug
