---
id: turn_on_garden_electricity
alias: Turn On Garden Electricity
triggers:
  - trigger: state              # The plug is off
    entity_id: switch.garden_plug
    to: "off"
  - trigger: homeassistant      # Home Assistant has just been started
    event: start
    id: homeassistant_start
actions:
  - action: switch.turn_on      # Turn on the plug
    target:
      entity_id: switch.garden_plug
