---
id: turn_off_kitchen_hot_water_kettle
alias: Turn Off Kitchen Hot Water Kettle
triggers:
  - trigger: numeric_state      # Energy is not consumed for 5 seconds
    entity_id: sensor.kitchen_hot_water_kettle_plug_power
    below: 1
    for:
      seconds: 5
    id: kettle_finished
  - trigger: state              # The plug is on for 1 minute
    entity_id: switch.kitchen_hot_water_kettle_plug
    to: "on"
    for:
      minutes: 1
    id: timeout
  - trigger: homeassistant      # Home Assistant has just been started
    event: start
    id: homeassistant_start
conditions:
  - condition: numeric_state    # Do not turn off the plug when the kettle is consuming energy
    entity_id: sensor.kitchen_hot_water_kettle_plug_power
    below: 1
actions:
  - action: switch.turn_off     # Turn off the plug
    target:
      entity_id: switch.kitchen_hot_water_kettle_plug
