---
# https://github.com/Antrac1t/HomeAssistant-EGDdistribuce
# https://eru.gov.cz/energeticky-regulacni-vestnik-82023

binary_sensor:
  - platform: egddistribuce
    name: Electricity Distribution Tariff 2025
    psc: smart
    code_a: d57           # Území EG.D - distribuce + systémové služby + OZE + daň
    price_vt: "1.41298"   # (718.76 + 170.92 + 495 + 28,30) / 1000
    price_nt: "0.91886"   # (224.64 + 170.92 + 495 + 28,30) / 1000
