---
id: hourly_grid_energy_tarrif
alias: Hourly grid energy tarrif
triggers:
  - trigger: time_pattern   # Every hour
    minutes: 0
    seconds: 0
  - trigger: homeassistant  # Home Assistant has just been started
    event: start
actions:
  - action: select.select_option
    target:
      entity_id: select.daily_grid_energy_import
    data:
      option: "hour_{{ '{0:02}'.format(utcnow().hour) }}"

