---
id: turn_off_heat_pump_boost
alias: Turn off heat pump boost
trigger_variables:
  battery_capacity: sensor.solax_battery_capacity
  grid_export: sensor.solax_grid_export
  hp_boost_switch: switch.shellypro3_ec626089f4bc_switch_1
triggers:
  - trigger: numeric_state      # Battery capacity below 95%
    entity_id: sensor.solax_battery_capacity
    below: 95
  - trigger: numeric_state      # Energy is not exported to the grid for 1 minute
    entity_id: sensor.solax_grid_export
    below: 1
    for:
      minutes: 1
  - trigger: homeassistant      # Home Assistant has just been started
    event: start
  - trigger: homeassistant      # Home Assistant is shutting down
    event: shutdown
conditions:
  - condition: state
    entity_id: switch.heat_pump_relay_boost_heat_pump
    state: "on"
actions:
  - action: switch.turn_off
    target:
      entity_id: switch.heat_pump_relay_boost_heat_pump

