---
automation:
  - alias: Bedroom Right Bed Light Controller
    id: 23e596c4-5831-4859-a262-60e3dfc288f6
    triggers:
      - trigger: state              # Switch button pressed
        entity_id: event.bedroom_right_bed_switch_action
        not_from: unavailable
        not_to: unavailable
        # Do not put any To or From or Attribute lines in trigger
        # If you do, you cannot push same button twice
    actions:
      - variables:
          trigger_action: "{{ trigger.to_state.attributes.event_type }}"
          brightness: "{{ state_attr('light.bedroom_right_bed_light', 'brightness') | int(0) }}"
      - choose:
          - conditions:             # Increase the brightness of the light
              - condition: template
                value_template: "{{ trigger_action == 'on' }}"
              - condition: template
                value_template: "{{ brightness < 255 }}"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.bedroom_right_bed_light
                data:
                  brightness_step: 51   # +20%
                  transition: 0.2
          - conditions:             # Decrease the brightness of the light
              - condition: template
                value_template: "{{ trigger_action == 'off' }}"
              - condition: template
                value_template: "{{ brightness > 0 }}"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.bedroom_right_bed_light
                data:
                  brightness_step: -51  # -20%
                  transition: 0.2
          - conditions:             # Turn on the light
              - condition: template
                value_template: "{{ trigger_action == 'brightness_move_up' }}"
              - condition: template
                value_template: "{{ brightness < 255 }}"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.bedroom_right_bed_light
                data:
                  brightness: 255   # 100%
                  transition: 0.2
          - conditions:             # Turn off the light
              - condition: template
                value_template: "{{ trigger_action == 'brightness_move_down' }}"
              - condition: template
                value_template: "{{ brightness > 0 }}"
            sequence:
              - action: light.turn_off
                target:
                  entity_id: light.bedroom_right_bed_light
                data:
                  transition: 0.2
          - conditions:             # Increase the brightness of the bed lights
              - condition: template
                value_template: "{{ trigger_action == 'arrow_right_click' }}"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.bedroom_bed_lights
                data:
                  brightness: "{{ brightness + 51 }}" # +20%
                  transition: 0.2
          - conditions:             # Decrease the brightness of the bed lights
              - condition: template
                value_template: "{{ trigger_action == 'arrow_left_click' }}"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.bedroom_bed_lights
                data:
                  brightness: "{{ brightness - 51 }}" # -20%
                  transition: 0.2
          - conditions:             # Turn on all the lights in the room
              - condition: template
                value_template: "{{ trigger_action == 'arrow_right_hold' }}"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.bedroom_lights
                data:
                  brightness: 255   # 100%
                  transition: 0.2
          - conditions:             # Turn off all the lights in the room
              - condition: template
                value_template: "{{ trigger_action == 'arrow_left_hold' }}"
            sequence:
              - action: light.turn_off
                target:
                  entity_id: light.bedroom_lights
                data:
                  transition: 0.2
