---
id: greenhouse_heating_controller
alias: Greenhouse Heating Controller
triggers:
  - trigger: numeric_state      # Temperature exceeds upper limit
    entity_id: sensor.greenhouse_soil_temperature
    above: 10
    for:
      minutes: 1
  - trigger: numeric_state      # Temperature exceeds lower limit
    entity_id: sensor.greenhouse_soil_temperature
    below: 5
    for:
      minutes: 1
  - trigger: state              # The heating has been enabled or disabled
    entity_id: input_boolean.greenhouse_heating
  - trigger: state              # The ventilation has been enabled
    entity_id: input_boolean.greenhouse_ventilation
    to: "on"
  - trigger: homeassistant      # Home Assistant has just been started
    event: start
actions:
  - choose:
      - conditions:             # Disable heating if ventilation has been enabled
          - condition: state
            entity_id: input_boolean.greenhouse_ventilation
            state: "on"
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.greenhouse_heating
      - conditions:             # Turn on heating if temperature exceeds lower limit
          - condition: state
            entity_id: input_boolean.greenhouse_heating
            state: "on"
          - condition: numeric_state
            entity_id: sensor.greenhouse_soil_temperature
            below: 5
        sequence:
          - action: switch.turn_on
            target:
              entity_id: switch.greenhouse_plug
      - conditions:             # Turn off heating if temperature exceeds higher limit
          - condition: state
            entity_id: input_boolean.greenhouse_heating
            state: "on"
          - condition: numeric_state
            entity_id: sensor.greenhouse_soil_temperature
            above: 10
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.greenhouse_plug
      - conditions:             # Turn off heating if it has been disabled
          - condition: state
            entity_id: input_boolean.greenhouse_heating
            state: "off"
          - condition: state
            entity_id: input_boolean.greenhouse_ventilation
            state: "off"
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.greenhouse_plug
