---
# https://andrew-codechimp.github.io/HA-Battery-Notes/community/#battery-replaced
id: baterry_replaced
alias: Battery Replaced
description: Battery Replaced
trigger:
  - platform: event
    event_type: battery_notes_battery_increased
action:
  - service: battery_notes.set_battery_replaced
    data:
      device_id: "{{ trigger.event.data.device_id }}"
      source_entity_id: "{{ trigger.event.data.source_entity_id }}"
mode: queued
max: 30   # Must be higher than the number of batteries
