---
# https://andrew-codechimp.github.io/HA-Battery-Notes/community/#check-battery-low-daily-reminder
id: daily_battery_low_check
alias: Daily Battery Low Check
description: Check whether a battery is low
trigger:
  - platform: state
    entity_id:
      - schedule.battery_maintenance
    to: "on"
condition: []
action:
  - service: battery_notes.check_battery_low
mode: single