---
# https://andrew-codechimp.github.io/HA-Battery-Notes/community/#check-battery-last-reported-daily
id: daily_battery_not_reported_check
alias: Daily Battery Not Reported Check
description: Check whether a battery has reported
trigger:
  - platform: state
    entity_id:
      - schedule.battery_maintenance
    to: "on"
action:
  - service: battery_notes.check_battery_last_reported
    data:
      days_last_reported: 2
