---
automation:
  - alias: Kitchen Hot Water Kettle Controller
    description: Auto-Off Electrical Outlet
    id: ebeb1eef-8c76-41da-afea-72df646bb69b
    use_blueprint:
      path: prehor/auto-off-electrical-outlet.yaml
      input:
        outlet_switch_entity: switch.kitchen_hot_water_kettle_plug
        outlet_power_sensor_entity: sensor.kitchen_hot_water_kettle_plug_power
        outlet_power_threshold: 1
        outlet_turn_on_timeout:
          minutes: 1
        outlet_turn_off_delay:
          seconds: 30
