---
automation:
  - alias: Kitchen Tea Kettle Controller
    description: Auto-Off Electrical Outlet
    id: 50fb36b8-bced-41c0-be38-3253ad1337f1
    use_blueprint:
      path: prehor/auto-off-electrical-outlet.yaml
      input:
        outlet_switch_entity: switch.kitchen_tea_kettle_plug
        outlet_power_sensor_entity: sensor.kitchen_tea_kettle_plug_power
        outlet_power_threshold: 1
        outlet_turn_on_timeout:
          minutes: 1
        outlet_turn_off_delay:
          seconds: 30
