---
# TODO: Allow changing the value of limits

automation:
  - alias: Greenhouse Heating Controller
    id: 4c1168a2-ceba-434a-91b8-ea08543d5438
    triggers:
      - trigger: numeric_state      # Temperature exceeds upper limit
        entity_id: sensor.greenhouse_soil_temperature
        above: 10
      - trigger: numeric_state      # Temperature exceeds lower limit
        entity_id: sensor.greenhouse_soil_temperature
        below: 5
      - trigger: state              # Plug became available
        entity_id: switch.greenhouse_plug
        from:
          - unavailable
      - trigger: state              # Mode has just been changed to heating
        entity_id: input_select.greenhouse_plug_mode
        to: Heating
        id: initialize
      - trigger: homeassistant      # Home Assistant has just been started
        event: start
        id: initialize
      - trigger: homeassistant      # Home Assistant going to be shutdown
        event: shutdown
        id: shutdown
    conditions:
      - condition: state            # Mode is ventilation
        entity_id: input_select.greenhouse_plug_mode
        state: Heating
    actions:
      - choose:
          - conditions:            # Turn off the heating when the homeassistant turns off
              - condition: trigger
                id: shutdown
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.greenhouse_plug
          - conditions:             # Turn on heating if temperature is below the upper limit
              - condition: numeric_state
                entity_id: sensor.greenhouse_soil_temperature
                below: 10
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.greenhouse_plug
          - conditions:             # Turn off heating if temperature is above the upper limit
              - condition: numeric_state
                entity_id: sensor.greenhouse_soil_temperature
                above: 10
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.greenhouse_plug
          - conditions:            # Turn off heating when heating mode is initialized
              - condition: trigger
                id: initialize
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.greenhouse_plug
