---
id: 419fc702-e113-4253-9493-d1ce5840cc97
alias: Keep Room Hana Computer Plug On
triggers:
  - trigger: state              # The plug has been switched off
    entity_id: switch.room_hana_computer_plug
    to: "off"
  - trigger: homeassistant      # Home Assistant has just been started
    event: start
    id: homeassistant_start
actions:
  - action: switch.turn_on      # Turn on the plug
    target:
      entity_id: switch.room_hana_computer_plug
